import type { Metadata } from "next"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

function Layout({ children }: { children: React.ReactNode }) {
	return (
		<html>
			<body>
				<main>{children}</main>
			</body>
		</html>
	)
}

export default Layout
