import Header from "@/components/header";
import { ChildrenParams } from "@/interfaces/params";
import type { Metadata } from "next"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

interface LayoutProps {
	children: React.ReactNode,
}

function Layout({children}: LayoutProps) {
	const params: ChildrenParams = JSON.parse(children?.props.childPropSegment.slice(9))

	return (
		<html>
			<body>
				<Header {...params} />
				<main>{children}</main>
			</body>
		</html>
	)
}

export default Layout
